name: Playwright Tests (Docker)

on:
  push:
    branches:
      - main
      - feature/*
      - develop
  pull_request:
    branches:
      - main
      - feature/*
      - develop
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/your-org/your-playwright-java-image:latest  # Replace with your built image

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        run: npx playwright test

      - name: Generate Allure report
        run: npm run allure:generate

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-report