name: Playwright Tests in Docker

on:
  push:
    branches: [main, qa, dev, feature/*]
  pull_request:
    branches: [main, qa, dev, feature/*]
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t my-playwright-runner -f Dockerfile.playwright .

      - name: Run Playwright Tests in Docker
        run: docker run --rm my-playwright-runner

      - name: Copy Allure Report from Docker container
        run: |
          docker create --name temp-runner my-playwright-runner
          docker cp temp-runner:/app/allure-report ./allure-report
          docker rm temp-runner

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-report
