name: Playwright Tests (Docker)

on:
  push:
    branches:
      - main
      - feature/*
      - develop
  pull_request:
    branches:
      - main
      - feature/*
      - develop
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright:v1.44.1-jammy  # Official Playwright Docker image

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        run: npx playwright test

      - name: Install Allure CLI
        run: npm install -g allure-commandline --save-dev

      - name: Generate Allure report
        run: npm run allure:generate

      - name: Upload Allure Report as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-report
