name: Playwright Tests in Docker

on:
  push:
    branches: [main, qa, dev, feature/*]
  pull_request:
    branches: [main, qa, dev, feature/*]
  workflow_dispatch: 
    inputs:
      tag:
        description: 'Test tag to filter by (e.g., @smoke)'
        required: false
        default: ''
      browser:
        description: 'Browser to run tests on'
        required: true
        default: 'chromium'
      workers:
        description: 'Number of parallel workers'
        required: false
        default: '2'
      retries:
        description: 'Retry count'
        required: false
        default: '1'
      test_env:
        description: 'Test environment (qa1, dev, etc.)'
        required: true
        default: 'qa1'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.event.inputs.tag && format('--grep {0}', github.event.inputs.tag) || '' }}
      TEST_ENV: ${{ github.event.inputs.test_env || 'qa1' }}
      BROWSER: ${{ github.event.inputs.browser || 'chromium' }}
      WORKERS: ${{ github.event.inputs.workers || '2' }}
      RETRIES: ${{ github.event.inputs.retries || '1' }} 

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t my-playwright-runner -f Dockerfile.playwright .

      - name: Run Playwright Tests in Docker
        run: |
          docker run --name temp-runner \
            -e TAG="--grep ${TAG}" \
            -e TEST_ENV=${{ env.TEST_ENV }} \
            -e BROWSER=${{ env.BROWSER }} \
            -e WORKERS=${{ env.WORKERS }} \
            -e RETRIES=${{ env.RETRIES }} \
            my-playwright-runner \
            npm run test:allure

      - name: Copy Allure report
        run: |
          docker cp temp-runner:/app/allure-report ./allure-report
          docker rm temp-runner

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-report

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
