name: Playwright Tests in Docker

on:
  push:
    branches: [main, qa, dev, feature/*]
  pull_request:
    branches: [main, qa, dev, feature/*]
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-playwright-runner -f .github/docker/Dockerfile.playwright .

      - name: Run Playwright tests in container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            my-playwright-runner \
            npx playwright test

      - name: Generate Allure report
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            my-playwright-runner \
            npm run allure:generate

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-report
